# Generated by Django 3.0.7 on 2020-06-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200611_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='language',
        ),
        migrations.AddField(
            model_name='language',
            name='name',
            field=models.CharField(default=None, help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)", max_length=200),
            preserve_default=False,
        ),
    ]
